import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GoogleGenerativeAI } from '@google/generative-ai';

@Injectable()
export class AiService {
  private readonly genAI: GoogleGenerativeAI | null = null;

  constructor(private readonly configService: ConfigService) {
    const apiKey = this.configService.get<string>('GEMINI_API_KEY');
    if (apiKey) {
      this.genAI = new GoogleGenerativeAI(apiKey);
    }
  }

  async generateSummary(prompt: string): Promise<string> {
    if (this.configService.get<string>('GEMINI_API_KEY') === 'mock-key') {
      return 'This is a mock 3-sentence summary of the task. It has been generated by the mock AI service. Testing cache and invalidation works.';
    }
    if (!this.genAI) {
      throw new Error('GEMINI_API_KEY is not configured');
    }
    const model = this.genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
    const result = await model.generateContent(prompt);
    const response = result.response;
    return response.text();
  }
}
